default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode # 追加

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: calendar_development

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: calendar_test

# Herokuデプロイ時に再度見直す
production:
  <<: *default
  # database: db/production.sqlite3 変更
  database: calendar_production
  username: calendar # 追加
  password: <%= ENV['STOCK_DATABASE_PASSWORD'] %> # 追加